"""tables

Revision ID: 2c77bc9481cb
Revises: 37689dfbc011
Create Date: 2024-04-03 18:42:17.310474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c77bc9481cb'
down_revision = '37689dfbc011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('Author', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('Description', sa.String(), nullable=False))
        batch_op.alter_column('issued_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('returned_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('admin', 'member'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'member'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('returned_at',
               existing_type=sa.String(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('issued_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('Description')
        batch_op.drop_column('Author')
        batch_op.drop_column('image_url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
