"""tables

Revision ID: 39573a41fbf8
Revises: 2c77bc9481cb
Create Date: 2024-04-03 20:10:54.371892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39573a41fbf8'
down_revision = '2c77bc9481cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Book_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'books', ['Book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Book_id')

    # ### end Alembic commands ###
