"""update books table model

Revision ID: 611fbf9afcf7
Revises: fd700ea47dc6
Create Date: 2024-05-17 16:20:18.845287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611fbf9afcf7'
down_revision = 'fd700ea47dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initialCount', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('initialCount')

    # ### end Alembic commands ###
